### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by stevenjoezhang** [next-theme/hexo-generator-searchdb#3]
- [ ] Search filters on archives / cats / tags (https://github.com/iissnan/hexo-theme-next/issues/424, https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/all-categories/#posts-list-releases, http://litten.me)
- [ ] Local search obscure lookup (https://github.com/iissnan/hexo-theme-next/issues/1695)
- [ ] Control characters issue (https://github.com/theme-next/hexo-theme-next/issues/1167, https://github.com/next-theme/hexo-theme-next/issues/235)
- [ ] Option to sort local search result by date
- [ ] Strip code blocks (#23)
